# Generated by Django 3.1.1 on 2020-09-13 02:03

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=200),
        ),
    ]
