# Generated by Django 3.1.1 on 2020-09-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200913_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number_of_plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sum_of_moods',
            field=models.IntegerField(default=0),
        ),
    ]
