# Generated by Django 3.1.1 on 2020-09-13 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200913_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
